# -*- coding: utf-8 -*-
"""Copia de LCDNBot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10cYlRZI3ByCZfXo4B9HpL-Srp9EcWojd
"""

! pip install pyTelegramBotAPI
import telebot
import time
from telebot import types
from telebot.types import InlineKeyboardMarkup, InlineKeyboardButton

from google.colab import drive
drive.mount('/content/drive')

TELEGRAM_TOKEN = '7138846827:AAG1WFaZ_FCe0toJ7gvEP81O9oZL2sBEyoU'
bot = telebot.TeleBot(TELEGRAM_TOKEN)

@bot.message_handler(commands=['start'])
def cmd_start(message):
    markup = types.ReplyKeyboardMarkup(input_field_placeholder='Elige un tipo de usuario:', resize_keyboard=True, one_time_keyboard=False)
    markup.add("Soy estudiante", "Soy aspirante", "Acerca de la URC")
    msg = bot.send_message(message.chat.id, "Bienvenido al bot de la Licenciatura en Ciencia de Datos para Negocios. Para comenzar, elige una opción:", reply_markup=markup)
    bot.register_next_step_handler(msg, respuesta)

def respuesta(message):
    if message.text == "Soy estudiante":
        markup = types.ReplyKeyboardMarkup(input_field_placeholder='Selecciona una opción:', row_width=2, one_time_keyboard=False)
        markup.add("Plan de estudios", "Administración escolar", "Registro a extraordinarios", "Calendario escolar", "Menú anterior")
        msg = bot.send_message(message.chat.id, "Selecciona la información que deseas obtener:", reply_markup=markup)
        bot.register_next_step_handler(msg, estudiante)
    elif message.text == "Soy aspirante":
        markup = types.ReplyKeyboardMarkup(row_width=2, one_time_keyboard=False)
        markup.add("Convocatoria", "¿Cómo puedo ingresar a la URC?", "U. A. donde se imparte la Licenciatura", "Modalidades", "¿Qué es la Ciencia de datos?", "Plan de estudios", "Menú anterior")
        msg = bot.send_message(message.chat.id, "Selecciona la información que deseas obtener:", reply_markup=markup)
        bot.register_next_step_handler(msg, aspirante)
    elif message.text == "Acerca de la URC":
        markup = types.ReplyKeyboardMarkup(input_field_placeholder='Presiona un botón:', row_width=1, resize_keyboard=True)
        markup.add("Historia de la URC", "Unidades académicas", "Licenciaturas Presenciales", "Licenciaturas a Distancia", "Sitio oficial", "Redes sociales", "Menú anterior")
        msg = bot.send_message(message.chat.id, "Selecciona la información que deseas obtener:", reply_markup=markup)
        bot.register_next_step_handler(msg, acerca)

def estudiante(message):
    if message.text == "Plan de estudios":
        chat_id = message.chat.id
        file_path = '/content/drive/MyDrive/Bot/Lcdn.pdf'
        with open(file_path, 'rb') as document:
         msg = bot.send_document(chat_id, document)
        bot.register_next_step_handler(msg, estudiante)
    elif message.text == "Administración escolar":
        markup = InlineKeyboardMarkup(row_width=1)
        b1 = InlineKeyboardButton("Solicitud de historial académico", url='https://docs.google.com/forms/d/e/1FAIpQLScHY8Ku_FHSaohlDjl0xL6zn5kb-4v0FX9-mjONVQHhImOgYQ/viewform')
        b2 = InlineKeyboardButton("Solicitud de Constancia de estudios", url='https://docs.google.com/forms/d/e/1FAIpQLScHY8Ku_FHSaohlDjl0xL6zn5kb-4v0FX9-mjONVQHhImOgYQ/viewform')
        b3 = InlineKeyboardButton("Solicitud de Constancia de Créditos", url='https://docs.google.com/forms/d/e/1FAIpQLSejxT9J_SUYrcFVxlUm5SJkGxKjxpwFPoGVcRgw4nzZ4RdRTw/viewform')
        b4 = InlineKeyboardButton("Solicitud de Credencial Nuevo Ingreso", url='https://docs.google.com/forms/d/e/1FAIpQLSeRzid4NUUAH8hbvCHx-3A4N_55JLdwxS_WM6jYhwY06kC-ZA/closedform')
        b5 = InlineKeyboardButton("Solicitud Extemporánea de Credencial", url='https://docs.google.com/forms/d/e/1FAIpQLScv83fV03M8jRLLawxCkYbBDD7TKF2ow7vc0acO7-KTEwdcZg/closedform')
        b6 = InlineKeyboardButton("Solicitud de Seguro Facultativo", url='https://docs.google.com/forms/d/e/1FAIpQLScNrg5tra3Q7Fdskz-Ty7T_YTfvbn1pEvPgSd7b-TANnmtJlw/viewform')
        b7 = InlineKeyboardButton("Solicitud de Baja Temporal", url='https://docs.google.com/forms/d/e/1FAIpQLSfL8rXFNjBkncI560KpAenK5onmUSCThSXLKg_msVXWiwr7Zg/viewform')
        b8 = InlineKeyboardButton("Solicitud de Baja Definitiva", url='https://docs.google.com/forms/d/e/1FAIpQLSf1u18sKYiXexfQwRvc_yrPq_a4i85SvKUgkHP6_Iywa7LnZQ/viewform')
        b9 = InlineKeyboardButton("Solicitud de Correción de Datos", url='https://docs.google.com/forms/d/e/1FAIpQLSeWgNmAvUtaPFHZam3PyLQKrKdcrLWibhEeYGshovcgrKOWrw/viewform')
        b10 = InlineKeyboardButton("Solicitud de Correción de Historial", url='https://docs.google.com/forms/d/e/1FAIpQLSdiaSbXjT8sRdDRE2Y1nVSVY88S4uByICwQZ_taOnOZofZM5A/viewform')
        b11 = InlineKeyboardButton("SUBES Correción de Datos", url='https://docs.google.com/forms/d/e/1FAIpQLSdh9AjEaGVdV4XA_ptJZxzU4xXboFfDzV2CXXlBddVQNdr7zg/viewform')
        markup.add(b1, b2, b3, b4, b5, b6, b7, b8, b9, b10, b11)
        msg = bot.send_message(message.chat.id, "Pulsa un botón:", reply_markup=markup)
        bot.register_next_step_handler(msg, estudiante)
    elif message.text == "Registro a extraordinarios":
        markup = InlineKeyboardMarkup(row_width=1)
        bt1 = InlineKeyboardButton("Registro a extraordinarios", url='https://edu.rcastellanos.cdmx.gob.mx/registro_extraordinarios/')
        markup.add(bt1)
        msg = bot.send_message(message.chat.id, 'Este es el enlace de resigtro. Si existe alguna duda, te recomiendo acercarte a tu jefa o jefe de carrera, quien te proporcionará más detalles sobre este tema.', reply_markup=markup)
        bot.register_next_step_handler(msg, estudiante)
    elif message.text == "Calendario escolar":
        chat_id = message.chat.id
        file_path = '/content/drive/MyDrive/Bot/Calendario.pdf'
        with open(file_path, 'rb') as document:
         msg = bot.send_document(chat_id, document)
        bot.register_next_step_handler(msg, estudiante)
    elif message.text == "Menú anterior":
        cmd_start(message)
    else:
        msg = bot.send_message(message.chat.id, "Por favor, selecciona una opción válida.")
        bot.register_next_step_handler(msg, estudiante)

def aspirante(message):
    if message.text == "Convocatoria":
         chat_id = message.chat.id
         file_path = '/content/drive/MyDrive/Bot/Convocatoria_2024-2.pdf'
         with open(file_path, 'rb') as document:
          msg = bot.send_document(chat_id, document)
         bot.register_next_step_handler(msg, aspirante)
    elif message.text == "¿Cómo puedo ingresar a la URC?":
        chat_id = message.chat.id
        file_path = '/content/drive/MyDrive/Bot/Proceso_de_admision.pdf'
        with open(file_path, 'rb') as document:
         msg = bot.send_document(chat_id, document)
         bot.register_next_step_handler(msg, aspirante)
    elif message.text == "U. A. donde se imparte la Licenciatura":
        markup = InlineKeyboardMarkup(row_width=1)
        bt1 = InlineKeyboardButton("Unidad Académica Coyoacán", url='https://www.google.com/maps/place/Universidad+Rosario+Castellanos+Campus+Coyoac%C3%A1n/@19.3076199,-99.1618679,17z/data=!4m15!1m8!3m7!1s0x85ce0046fd0388c5:0x13520406ae5f824e!2sSan+Eleuterio,+Pedregal+de+Sta+%C3%9Arsula,+04600+Ciudad+de+M%C3%A9xico,+CDMX!3b1!8m2!3d19.3112218!4d-99.1599758!16s%2Fg%2F1xgzc378!3m5!1s0x85ce010143ce04ff:0x595a903fd65a4fc9!8m2!3d19.3088445!4d-99.1598973!16s%2Fg%2F11h4g7zb3x?entry=ttu')
        bt2 = InlineKeyboardButton("Unidad Académica Gustavo A. Madero", url='https://www.google.com/maps/place/Universidad+Rosario+Castellanos+-+Campus+Gustavo+A.+Madero+II/@19.5080195,-99.125328,17z/data=!3m1!4b1!4m5!3m4!1s0x85d1f89ac730ad27:0xb5e7f03eea6cfd28!8m2!3d19.5080195!4d-99.125328')
        bt3 = InlineKeyboardButton("Unidad Académica La Magdalena Contreras", url='https://www.google.com/maps/place/UACM+Magdalena+Contreras/@19.3094126,-99.257732,17z/data=!3m1!4b1!4m6!3m5!1s0x85cdff40753ab33d:0x1dc7e6c58700bbe0!8m2!3d19.3094126!4d-99.257732!16s%2Fg%2F11c6pt71gb?entry=ttu')
        markup.add(bt1, bt2, bt3,)
        msg = bot.send_message(message.chat.id, "Pulsa un botón:", reply_markup=markup)
        bot.register_next_step_handler(msg, aspirante)
    elif message.text == "Modalidades":
        chat_id = message.chat.id
        file_path = '/content/drive/MyDrive/Bot/modalidades.png'
        with open(file_path, 'rb') as photo:
         msg = bot.send_photo(chat_id, photo)
         bot.register_next_step_handler(msg, aspirante)
    elif message.text == "¿Qué es la Ciencia de datos?":
        chat_id = message.chat.id
        file_path = '/content/drive/MyDrive/Bot/definicion_cienciadedatos.png'
        with open(file_path, 'rb') as photo:
         msg = bot.send_photo(chat_id, photo)
         bot.register_next_step_handler(msg, aspirante)
    elif message.text == "Plan de estudios":
        chat_id = message.chat.id
        file_path = '/content/drive/MyDrive/Bot/Lcdn.pdf'
        with open(file_path, 'rb') as document:
         msg = bot.send_document(chat_id, document)
         bot.register_next_step_handler(msg, aspirante)
    elif message.text == "Menú anterior":
        cmd_start(message)
    else:
        msg = bot.send_message(message.chat.id, "Por favor, selecciona una opción válida.")
        bot.register_next_step_handler(msg, aspirante)

def acerca(message):
    if message.text == "Historia de la URC":
       chat_id = message.chat.id
       file_path = '/content/drive/MyDrive/Bot/Historia.pdf'
       with open(file_path, 'rb') as document:
        msg = bot.send_document(chat_id, document)
       bot.register_next_step_handler(msg, acerca)
    elif message.text == "Unidades académicas":
        markup = InlineKeyboardMarkup(row_width=1)
        m1 = InlineKeyboardButton("Unidad Académica Azcapotzalco", url='https://www.google.com/maps/place/IEMS+Bachillerato+Universitario+%22Plantel+Azcapotzalco+2%22/@19.4882354,-99.20961,17z/data=!3m1!4b1!4m6!3m5!1s0x85d2028d66905405:0x6710d00595fd7110!8m2!3d19.4882354!4d-99.20961!16s%2Fg%2F11dyp5sgdg?entry=ttu')
        m2 = InlineKeyboardButton("Unidad Académica Coyoacán", url='https://www.google.com/maps/place/Universidad+Rosario+Castellanos+Campus+Coyoac%C3%A1n/@19.3076199,-99.1618679,17z/data=!4m15!1m8!3m7!1s0x85ce0046fd0388c5:0x13520406ae5f824e!2sSan+Eleuterio,+Pedregal+de+Sta+%C3%9Arsula,+04600+Ciudad+de+M%C3%A9xico,+CDMX!3b1!8m2!3d19.3112218!4d-99.1599758!16s%2Fg%2F1xgzc378!3m5!1s0x85ce010143ce04ff:0x595a903fd65a4fc9!8m2!3d19.3088445!4d-99.1598973!16s%2Fg%2F11h4g7zb3x?entry=ttu')
        m3 = InlineKeyboardButton("Unidad Académica Gustavo A. Madero", url='https://www.google.com/maps/place/Universidad+Rosario+Castellanos+Campus+Gustavo+A.+Madero/@19.4500746,-99.0860767,16z/data=!4m15!1m8!3m7!1s0x85d1fb96fc346cd1:0x1476441648985fcc!2sSan+Juan+de+Arag%C3%B3n+IV+Secc,+07979+Ciudad+de+M%C3%A9xico,+CDMX!3b1!8m2!3d19.4574586!4d-99.0654022!16s%2Fg%2F1tj6v4_g!3m5!1s0x85d1fbecc107804d:0x688710732587ac17!8m2!3d19.4522132!4d-99.0803604!16s%2Fg%2F11hbqydnls?entry=ttu')
        m4 = InlineKeyboardButton("Unidad Académica Justo Sierra", url='https://www.google.com/maps/place/Justo+Sierra+49,+Centro+Hist%C3%B3rico+de+la+Cdad.+de+M%C3%A9xico,+Centro,+Cuauht%C3%A9moc,+06020+Ciudad+de+M%C3%A9xico,+CDMX/@19.4352379,-99.1291425,17z/data=!3m1!4b1!4m6!3m5!1s0x85d1f9336070cb8f:0xa9d3a600b2c1b763!8m2!3d19.4352379!4d-99.1291425!16s%2Fg%2F11bw3__wl5?entry=ttu')
        m5 = InlineKeyboardButton("Unidad Académica La Magdalena Contreras", url='https://www.google.com/maps/place/UACM+Magdalena+Contreras/@19.3094126,-99.257732,17z/data=!3m1!4b1!4m6!3m5!1s0x85cdff40753ab33d:0x1dc7e6c58700bbe0!8m2!3d19.3094126!4d-99.257732!16s%2Fg%2F11c6pt71gb?entry=ttu')
        m6 = InlineKeyboardButton("Unidad Académica Casco Santo Tomás", url='https://www.google.com/maps/place/Universidad+Rosario+Castellanos+Campus+Santo+Tom%C3%A1s/@19.4527248,-99.170936,17.75z/data=!4m14!1m7!3m6!1s0x85d1f8bfbaeebabd:0x911c865be322e550!2sCanal+Once!8m2!3d19.4528818!4d-99.1697713!16s%2Fg%2F1tdkg_93!3m5!1s0x85d1f92e2e22f683:0x9bf299b231eba0ee!8m2!3d19.4523907!4d-99.1696341!16s%2Fg%2F11v6x0ctsx?authuser=0&entry=ttu')
        m7 = InlineKeyboardButton("Unidad Académica Licenciaturas a Distancia", url='https://www.google.com/maps/place/Universidad+Rosario+Castellanos+Campus+Santo+Tom%C3%A1s/@19.4527248,-99.170936,17.75z/data=!4m14!1m7!3m6!1s0x85d1f8bfbaeebabd:0x911c865be322e550!2sCanal+Once!8m2!3d19.4528818!4d-99.1697713!16s%2Fg%2F1tdkg_93!3m5!1s0x85d1f92e2e22f683:0x9bf299b231eba0ee!8m2!3d19.4523907!4d-99.1696341!16s%2Fg%2F11v6x0ctsx?authuser=0&entry=ttu')
        m8 = InlineKeyboardButton("Unidad Académica Euzkadi", url='https://www.google.com.mx/maps/place/Norte+45,+Euzkadi,+Azcapotzalco,+Ciudad+de+M%C3%A9xico,+CDMX/@19.478208,-99.1632962,19z/data=!3m1!4b1!4m6!3m5!1s0x85d1f8f5ec2d8d87:0x2476ce691601a59d!8m2!3d19.478208!4d-99.1632962!16s%2Fg%2F11rc9mnf5f?entry=ttu')
        m9 = InlineKeyboardButton("Unidad Académica Maza de Juárez", url='https://www.google.com.mx/maps/place//@19.3320568,-99.1709262,19z/data=!3m1!4b1?entry=ttu')
        m10 = InlineKeyboardButton("Unidad Académica Herrerías", url='https://www.google.com.mx/maps/place/PILARES+MILPA+ALTA/@19.193538,-99.0192678,19z/data=!4m6!3m5!1s0x85ce05a9457df927:0x75c1ad6c6eeeaa64!8m2!3d19.1934869!4d-99.0189335!16s%2Fg%2F11jp5wv17c?entry=ttu')
        m11 = InlineKeyboardButton("Unidad Académica Casa de Cultura Milpa Alta", url='https://www.google.com.mx/maps/place/Ol%C3%ADmpica+10,+Santa+Ana+Tlacotenco,+San+Jos%C3%A9,+Milpa+Alta,+12900+Ciudad+de+M%C3%A9xico,+CDMX/@19.1774345,-99.0031165,19z/data=!3m1!4b1!4m6!3m5!1s0x85ce1ab774ebf6f3:0xef60fa37fa6562a1!8m2!3d19.1774345!4d-99.0031165!16s%2Fg%2F11cs6cvn04?entry=ttu')
        m12 = InlineKeyboardButton("Unidad Académica PILARES Tierra Unida - Magdalena Contreras", url='https://www.google.com.mx/maps/place/PILARES+%22Tierra+Unida%22/@19.3019515,-99.26986,21z/data=!4m6!3m5!1s0x85cdff85b367dddf:0xcbf371db2dd709ef!8m2!3d19.3018447!4d-99.2696441!16s%2Fg%2F11szf2xvcj?entry=ttu')
        m13 = InlineKeyboardButton("Unidad Académica PILARES Oceanía - GAM ", url='https://www.google.com.mx/maps/place/PILARES+OCEAN%C3%8DA/@19.4510666,-99.0810156,18z/data=!4m6!3m5!1s0x85d1fb8b6f208e7d:0xb44c64fbdbb8dcc5!8m2!3d19.4510822!4d-99.0803211!16s%2Fg%2F11hf6nc_9t?entry=ttu')
        markup.add(m1, m2, m3, m4, m5, m6, m7, m8, m9, m10, m11, m12, m13)
        msg = bot.send_message(message.chat.id, "La Universidad Rosario Castellanos cuenta con varias unidades académicas distribuidas en la Ciudad de México", reply_markup=markup)
        bot.register_next_step_handler(msg, acerca)
    elif message.text == "Licenciaturas Presenciales":
       markup = InlineKeyboardMarkup(row_width=2)
       mk1 = InlineKeyboardButton("Lic. en Ciencias Ambientales para Zonas Urbanas", url='https://www.rcastellanos.cdmx.gob.mx/storage/app/media/PlanesEstudiosActualizados/Ciencias%20Ambientales%20para%20Zonas%20Urbanas.pdf')
       mk2 = InlineKeyboardButton("Lic. en Ciencias de Datos para Negocios", url='https://www.rcastellanos.cdmx.gob.mx/storage/app/media/PlanesEstudiosActualizados/Licenciatura%20en%20Ciencias%20de%20Datos%20para%20Negocios.pdf')
       mk3 = InlineKeyboardButton("Lic. en Contaduría y Finanzas", url='https://www.rcastellanos.cdmx.gob.mx/storage/app/media/PlanesEstudiosActualizados/licenciatura-en-contaduria-y-finanzas.pdf')
       mk4 = InlineKeyboardButton("Lic. en Derecho y Criminología", url='https://www.rcastellanos.cdmx.gob.mx/storage/app/media/PlanesEstudiosActualizados/Derecho%20y%20Criminologia.pdf')
       mk5 = InlineKeyboardButton("Lic. en Urbanismo y Desarrollo Metropolitano", url='https://www.rcastellanos.cdmx.gob.mx/storage/app/media/PlanesEstudiosActualizados/urbanismo-y-desarrollo-metropolitano.pdf')
       mk7 = InlineKeyboardButton("Lic. en Derecho y Seguridad Ciudadana", url='https://www.rcastellanos.cdmx.gob.mx/storage/app/media/PlanesEstudiosActualizados/L.%20Derecho%20y%20Seguridad%20Ciudadana.pdf')
       mk8 = InlineKeyboardButton("Lic. en Humanidades y Narrativas Multimedia", url='https://www.rcastellanos.cdmx.gob.mx/storage/app/media/PlanesEstudiosActualizados/Humanidades%20y%20Narrativas%20Multimedia.pdf')
       mk9 = InlineKeyboardButton("Lic. en Turismo", url='https://www.rcastellanos.cdmx.gob.mx/storage/app/media/PlanesEstudiosActualizados/Turismo.pdf')
       mk10 = InlineKeyboardButton("Lic. en Psicología", url='https://www.rcastellanos.cdmx.gob.mx/storage/app/media/PlanesEstudiosActualizados/psicologia.pdf')
       mk11 = InlineKeyboardButton("Lic. en Relaciones Internacionales", url='https://www.rcastellanos.cdmx.gob.mx/storage/app/media/PlanesEstudiosActualizados/Relaciones%20Internacionales.pdf')
       mk12 = InlineKeyboardButton("Lic. en Ciencias de la comunicacion", url='https://www.rcastellanos.cdmx.gob.mx/storage/app/media/PlanesEstudiosActualizados/ciencias-de-la-comunicacion.pdf')
       mk13 = InlineKeyboardButton("Ing. en Control y Automatización", url='https://www.rcastellanos.cdmx.gob.mx/storage/app/media/PlanesEstudiosActualizados/licenciatura-en-control-y-automatizacion-1.pdf')
       mk14 = InlineKeyboardButton("Lic. en Filosofía e Historia", url='https://www.rcastellanos.cdmx.gob.mx/storage/app/media/PlanesEstudiosActualizados/Lic_Filosofia_e_Historia.pdf')
       markup.add(mk1, mk2, mk3, mk4, mk5, mk7, mk8, mk9, mk10, mk11, mk12, mk13, mk14)
       msg = bot.send_message(message.chat.id, "La Universidad Rosario Castellanos ofrece diversas licenciaturas en áreas como Ciencia y Tecnología, Humanidades, Ciencias Sociales y Ciencias de la Salud. Pulsa para conocer el plan de estudios:", reply_markup=markup)
       bot.register_next_step_handler(msg, acerca)
    elif message.text == "Licenciaturas a Distancia":
       markup = InlineKeyboardMarkup(row_width=2)
       m1 = InlineKeyboardButton("Lic. en Administración y Comercio", url="https://www.rcastellanos.cdmx.gob.mx/storage/app/media/PlanesEstudiosActualizados/l-administracion-y-comercio.pdf")
       m2 = InlineKeyboardButton("Lic. en Tecnologías de la Información y Comunicación", url="https://www.rcastellanos.cdmx.gob.mx/storage/app/media/PlanesEstudiosActualizados/l-tecnologias-de-la-informacion.pdf")
       m3 = InlineKeyboardButton("Lic. en Mercadotecnia y Ventas", url="https://www.rcastellanos.cdmx.gob.mx/storage/app/media/PlanesEstudiosActualizados/L.%20Mercadotecnia%20y%20Ventas.pdf")
       m4 = InlineKeyboardButton("Lic. en Relaciones Internacionales", url="https://www.rcastellanos.cdmx.gob.mx/storage/app/media/PlanesEstudiosActualizados/Relaciones%20Internacionales.pdf")
       m5 = InlineKeyboardButton("Lic. en Psicología", url="https://www.rcastellanos.cdmx.gob.mx/storage/app/media/PlanesEstudiosActualizados/psicologia.pdf")
       m6 = InlineKeyboardButton("Lic. en Derecho y Criminología", url="https://www.rcastellanos.cdmx.gob.mx/storage/app/media/InfografiasActualizadasOCT2021/derechocriminologia.pdf")
       m7 = InlineKeyboardButton("Lic. en Humanidades y Narrativas Multimedia", url="https://www.rcastellanos.cdmx.gob.mx/storage/app/media/PlanesEstudiosActualizados/Humanidades%20y%20Narrativas%20Multimedia.pdf")
       m8 = InlineKeyboardButton("Lic. en Contaduría y Finanzas", url="https://www.rcastellanos.cdmx.gob.mx/storage/app/media/PlanesEstudiosActualizados/licenciatura-en-contaduria-y-finanzas.pdf")
       markup.add(m1, m2, m3, m4, m5, m7, m8)
       msg = bot.send_message(message.chat.id, "La Universidad Rosario Castellanos ofrece diversas licenciaturas en áreas como Ciencia y Tecnología, Humanidades, Ciencias Sociales y Ciencias de la Salud. Pulsa para conocer el plan de estudios:", reply_markup=markup)
       bot.register_next_step_handler(msg, acerca)
    elif message.text == "Sitio oficial":
        markup = InlineKeyboardMarkup(row_width=1)
        b1 = InlineKeyboardButton("Visita el sitio oficial", url='https://rcastellanos.cdmx.gob.mx/')
        markup.add(b1)
        msg = bot.send_message(message.chat.id, "Sitio oficial URC", reply_markup=markup)
        bot.register_next_step_handler(msg, acerca)
    elif message.text == "Redes sociales":
        markup = InlineKeyboardMarkup(row_width=2)
        a1 = InlineKeyboardButton('Facebook', url='https://www.facebook.com/universidadRCastelIanos')
        a2 = InlineKeyboardButton('YouTube', url='https://www.youtube.com/@UniversidadRCastellanos/featured')
        a3 = InlineKeyboardButton('Instagram', url='https://www.instagram.com/urcastellanos/?igsh=NTk4ZnZ5ZWdwZDNp')
        a4 = InlineKeyboardButton('TikTok', url='https://www.tiktok.com/@urcastellanos?_t=8mhijpiptPJ&_r=1')
        a5 = InlineKeyboardButton('X', url='https://x.com/urcastellanos_')
        markup.add(a1, a2, a3, a4, a5)
        msg = bot.send_message(message.chat.id, "Puedes seguir a la URC en sus redes sociales para estar al tanto de las últimas noticias, eventos y convocatorias:", reply_markup=markup)
        bot.register_next_step_handler(msg, acerca)
    elif message.text == "Menú anterior":
        cmd_start(message)
    else:
        msg = bot.send_message(message.chat.id, "Por favor, selecciona una opción válida.")
        bot.register_next_step_handler(msg, acerca)

# Inicia el bot
bot.infinity_polling()